/**
 * ============================================================
 * Sword Institute LMS
 * Resource Seeder
 * Version: 1.0.0
 * ============================================================
 *
 * Generates 50+ sample knowledge resources for testing and demos.
 *
 * Resources include:
 * - Books (15 resources)
 * - Videos (12 resources)
 * - Research Papers (8 resources)
 * - Podcasts (8 resources)
 * - Articles (7 resources)
 *
 * Spread across academies: AI Masters, Data Science Hub,
 * Business Academy, Leadership Institute
 *
 * ============================================================
 */

import {
    db,
    collection,
    addDoc,
    writeBatch,
    Timestamp,
} from "../firebase.js";

/* ============================================================
   CONSTANTS
============================================================ */

const RESOURCES_COLLECTION = "knowledge_resources";
const BATCH_SIZE = 25; // Firestore batch limit

/* ============================================================
   SAMPLE RESOURCES DATA
============================================================ */

const SAMPLE_RESOURCES = [
    // ============ BOOKS (15) ============
    {
        slug: "deep-learning-goodfellow",
        title: "Deep Learning",
        description: "A comprehensive introduction to deep learning by Ian Goodfellow, Yoshua Bengio, and Aaron Courville. This book covers neural networks, convolutional networks, and recurrent networks.",
        type: "book",
        difficulty: "advanced",
        estimatedTime: 600,
        academy: "AI Masters",
        author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        category: "Deep Learning",
        tags: ["deep-learning", "neural-networks", "machine-learning", "ai"],
        rating: 4.8,
        ratingCount: 1243,
        views: 15234,
        downloads: 3421,
        shares: 892,
        duration: "10 hours",
        pageCount: 775,
        language: "en",
        isPublished: true,
    },
    {
        slug: "pattern-recognition-bishop",
        title: "Pattern Recognition and Machine Learning",
        description: "A textbook covering machine learning and pattern recognition techniques. This is a foundational book for understanding ML algorithms from a Bayesian perspective.",
        type: "book",
        difficulty: "advanced",
        estimatedTime: 520,
        academy: "AI Masters",
        author: "Christopher Bishop",
        category: "Machine Learning",
        tags: ["machine-learning", "pattern-recognition", "bayesian"],
        rating: 4.7,
        ratingCount: 892,
        views: 10234,
        downloads: 2145,
        shares: 654,
        duration: "8 hours",
        pageCount: 738,
        language: "en",
        isPublished: true,
    },
    {
        slug: "python-crash-course",
        title: "Python Crash Course",
        description: "A beginner-friendly introduction to Python. Covers basics, data structures, functions, and real-world projects including web scraping and game development.",
        type: "book",
        difficulty: "beginner",
        estimatedTime: 180,
        academy: "AI Masters",
        author: "Eric Matthes",
        category: "Python",
        tags: ["python", "programming", "beginner"],
        rating: 4.9,
        ratingCount: 5234,
        views: 45321,
        downloads: 8921,
        shares: 3421,
        duration: "3 hours",
        pageCount: 544,
        language: "en",
        isPublished: true,
    },
    {
        slug: "data-science-from-scratch",
        title: "Data Science from Scratch",
        description: "Learn data science fundamentals without relying on libraries. Build algorithms from scratch to understand the core concepts deeply.",
        type: "book",
        difficulty: "intermediate",
        estimatedTime: 240,
        academy: "Data Science Hub",
        author: "Joel Grus",
        category: "Data Science",
        tags: ["data-science", "python", "algorithms"],
        rating: 4.6,
        ratingCount: 2134,
        views: 18234,
        downloads: 4123,
        shares: 1892,
        duration: "4 hours",
        pageCount: 330,
        language: "en",
        isPublished: true,
    },
    {
        slug: "natural-language-processing",
        title: "Natural Language Processing with Transformers",
        description: "Master NLP with transformer models. Covers BERT, GPT, attention mechanisms, and practical applications in text classification and generation.",
        type: "book",
        difficulty: "advanced",
        estimatedTime: 360,
        academy: "AI Masters",
        author: "Lewis Tunstall, Leandro von Werra, Thomas Wolf",
        category: "NLP",
        tags: ["nlp", "transformers", "deep-learning", "gpt"],
        rating: 4.7,
        ratingCount: 1432,
        views: 12543,
        downloads: 2987,
        shares: 876,
        duration: "6 hours",
        pageCount: 450,
        language: "en",
        isPublished: true,
    },
    {
        slug: "hands-on-machine-learning",
        title: "Hands-On Machine Learning",
        description: "Practical machine learning with scikit-learn and TensorFlow. Real-world projects and best practices for building production ML systems.",
        type: "book",
        difficulty: "intermediate",
        estimatedTime: 300,
        academy: "Data Science Hub",
        author: "Aurélien Géron",
        category: "Machine Learning",
        tags: ["machine-learning", "tensorflow", "scikit-learn"],
        rating: 4.8,
        ratingCount: 3214,
        views: 28934,
        downloads: 6123,
        shares: 2134,
        duration: "5 hours",
        pageCount: 595,
        language: "en",
        isPublished: true,
    },
    {
        slug: "good-to-great",
        title: "Good to Great",
        description: "How companies make the jump from good to great performance. Insights from 5-year research on successful companies and their transformation strategies.",
        type: "book",
        difficulty: "beginner",
        estimatedTime: 120,
        academy: "Business Academy",
        author: "Jim Collins",
        category: "Business",
        tags: ["business", "leadership", "strategy"],
        rating: 4.7,
        ratingCount: 8932,
        views: 67234,
        downloads: 12345,
        shares: 5432,
        duration: "2 hours",
        pageCount: 300,
        language: "en",
        isPublished: true,
    },
    {
        slug: "the-lean-startup",
        title: "The Lean Startup",
        description: "Build better products faster. Lean methodology for startups and established companies to validate ideas quickly and reduce waste.",
        type: "book",
        difficulty: "beginner",
        estimatedTime: 90,
        academy: "Business Academy",
        author: "Eric Ries",
        category: "Entrepreneurship",
        tags: ["startup", "lean", "innovation"],
        rating: 4.6,
        ratingCount: 5432,
        views: 45123,
        downloads: 8234,
        shares: 3421,
        duration: "1.5 hours",
        pageCount: 333,
        language: "en",
        isPublished: true,
    },
    {
        slug: "radical-candor",
        title: "Radical Candor",
        description: "Leadership approach combining caring with directness. Build trust while giving honest feedback and pushing for results.",
        type: "book",
        difficulty: "beginner",
        estimatedTime: 90,
        academy: "Leadership Institute",
        author: "Kim Scott",
        category: "Leadership",
        tags: ["leadership", "management", "communication"],
        rating: 4.7,
        ratingCount: 4123,
        views: 32145,
        downloads: 6234,
        shares: 2345,
        duration: "1.5 hours",
        pageCount: 320,
        language: "en",
        isPublished: true,
    },
    {
        slug: "atomic-habits",
        title: "Atomic Habits",
        description: "Transform your life through tiny changes. Science-backed strategies for building good habits and breaking bad ones.",
        type: "book",
        difficulty: "beginner",
        estimatedTime: 120,
        academy: "Leadership Institute",
        author: "James Clear",
        category: "Personal Development",
        tags: ["habits", "productivity", "self-improvement"],
        rating: 4.8,
        ratingCount: 12345,
        views: 89234,
        downloads: 18234,
        shares: 8934,
        duration: "2 hours",
        pageCount: 320,
        language: "en",
        isPublished: true,
    },
    {
        slug: "computer-vision-opencv",
        title: "Learning OpenCV",
        description: "Master computer vision with OpenCV library. Image processing, object detection, facial recognition, and real-time applications.",
        type: "book",
        difficulty: "intermediate",
        estimatedTime: 240,
        academy: "AI Masters",
        author: "Adrian Kaehler, Gary Bradski",
        category: "Computer Vision",
        tags: ["computer-vision", "opencv", "image-processing"],
        rating: 4.5,
        ratingCount: 1234,
        views: 9234,
        downloads: 1987,
        shares: 543,
        duration: "4 hours",
        pageCount: 530,
        language: "en",
        isPublished: true,
    },
    {
        slug: "reinforcement-learning",
        title: "Reinforcement Learning: An Introduction",
        description: "Foundational concepts in reinforcement learning. Covers Markov decision processes, temporal difference learning, and Q-learning algorithms.",
        type: "book",
        difficulty: "advanced",
        estimatedTime: 420,
        academy: "AI Masters",
        author: "Richard Sutton, Andrew Barto",
        category: "Reinforcement Learning",
        tags: ["reinforcement-learning", "algorithms", "game-ai"],
        rating: 4.6,
        ratingCount: 987,
        views: 8234,
        downloads: 1654,
        shares: 432,
        duration: "7 hours",
        pageCount: 526,
        language: "en",
        isPublished: true,
    },
    {
        slug: "business-analytics",
        title: "Business Analytics: Data-Driven Decision Making",
        description: "Learn to analyze business data and make informed decisions. Statistical methods, visualization, and real-world case studies.",
        type: "book",
        difficulty: "intermediate",
        estimatedTime: 180,
        academy: "Data Science Hub",
        author: "S. Christian Albright",
        category: "Business Analytics",
        tags: ["analytics", "business", "statistics"],
        rating: 4.4,
        ratingCount: 765,
        views: 6234,
        downloads: 1345,
        shares: 234,
        duration: "3 hours",
        pageCount: 432,
        language: "en",
        isPublished: true,
    },
    {
        slug: "database-design",
        title: "Database Design and Relational Theory",
        description: "Design robust databases. Normal forms, relational algebra, SQL optimization, and avoiding common pitfalls.",
        type: "book",
        difficulty: "intermediate",
        estimatedTime: 200,
        academy: "Data Science Hub",
        author: "C.J. Date",
        category: "Databases",
        tags: ["databases", "sql", "relational-design"],
        rating: 4.5,
        ratingCount: 654,
        views: 5123,
        downloads: 987,
        shares: 234,
        duration: "3.5 hours",
        pageCount: 400,
        language: "en",
        isPublished: true,
    },
    
    // ============ VIDEOS (12) ============
    {
        slug: "fastai-practical-deep-learning",
        title: "Practical Deep Learning for Coders",
        description: "Top-down approach to deep learning. Fast.ai course with cutting-edge techniques and practical projects.",
        type: "video",
        difficulty: "intermediate",
        estimatedTime: 480,
        academy: "AI Masters",
        author: "Jeremy Howard",
        category: "Deep Learning",
        tags: ["deep-learning", "fastai", "python", "cnn"],
        rating: 4.9,
        ratingCount: 3421,
        views: 45321,
        downloads: 8234,
        shares: 3421,
        videoLength: "8 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "stanford-cs229-ml",
        title: "Stanford CS229: Machine Learning",
        description: "Andrew Ng's legendary machine learning course. Comprehensive coverage of supervised and unsupervised learning.",
        type: "video",
        difficulty: "advanced",
        estimatedTime: 600,
        academy: "AI Masters",
        author: "Andrew Ng",
        category: "Machine Learning",
        tags: ["machine-learning", "stanford", "algorithms"],
        rating: 4.8,
        ratingCount: 8234,
        views: 89234,
        downloads: 15234,
        shares: 6234,
        videoLength: "10 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "python-for-everybody",
        title: "Python for Everybody",
        description: "Complete Python programming course from basics to advanced. Suitable for all experience levels.",
        type: "video",
        difficulty: "beginner",
        estimatedTime: 300,
        academy: "AI Masters",
        author: "Dr. Charles Severance",
        category: "Python",
        tags: ["python", "programming", "beginner"],
        rating: 4.7,
        ratingCount: 5432,
        views: 67234,
        downloads: 12345,
        shares: 5234,
        videoLength: "5 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "3blue1brown-linear-algebra",
        title: "Essence of Linear Algebra",
        description: "Visual, intuitive understanding of linear algebra concepts. Covers vectors, matrices, eigenvalues, and applications.",
        type: "video",
        difficulty: "beginner",
        estimatedTime: 150,
        academy: "Data Science Hub",
        author: "3Blue1Brown",
        category: "Mathematics",
        tags: ["linear-algebra", "mathematics", "visualization"],
        rating: 4.9,
        ratingCount: 12345,
        views: 234567,
        downloads: 34567,
        shares: 23456,
        videoLength: "2.5 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "huggingface-nlp",
        title: "Hugging Face NLP Course",
        description: "Learn state-of-the-art NLP with Hugging Face transformers library. Hands-on projects with real datasets.",
        type: "video",
        difficulty: "intermediate",
        estimatedTime: 360,
        academy: "AI Masters",
        author: "Hugging Face Team",
        category: "NLP",
        tags: ["nlp", "transformers", "huggingface"],
        rating: 4.8,
        ratingCount: 2134,
        views: 23456,
        downloads: 4567,
        shares: 1234,
        videoLength: "6 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "tensorflow-beginner",
        title: "TensorFlow for Beginners",
        description: "Introduction to TensorFlow and Keras. Build neural networks with Python for image classification and beyond.",
        type: "video",
        difficulty: "beginner",
        estimatedTime: 240,
        academy: "AI Masters",
        author: "TensorFlow Team",
        category: "Deep Learning",
        tags: ["tensorflow", "keras", "neural-networks"],
        rating: 4.7,
        ratingCount: 4321,
        views: 45678,
        downloads: 9012,
        shares: 3456,
        videoLength: "4 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "data-visualization-matplotlib",
        title: "Data Visualization with Matplotlib and Seaborn",
        description: "Master data visualization in Python. Create beautiful and informative plots for data analysis.",
        type: "video",
        difficulty: "beginner",
        estimatedTime: 120,
        academy: "Data Science Hub",
        author: "Alex The Analyst",
        category: "Data Science",
        tags: ["visualization", "matplotlib", "seaborn"],
        rating: 4.6,
        ratingCount: 2345,
        views: 23456,
        downloads: 5678,
        shares: 2345,
        videoLength: "2 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "agile-product-management",
        title: "Agile Product Management Masterclass",
        description: "Master agile methodologies in product management. Sprints, ceremonies, roadmap planning, and team collaboration.",
        type: "video",
        difficulty: "beginner",
        estimatedTime: 180,
        academy: "Business Academy",
        author: "Product School",
        category: "Product Management",
        tags: ["agile", "product-management", "scrum"],
        rating: 4.5,
        ratingCount: 1234,
        views: 12345,
        downloads: 3456,
        shares: 1234,
        videoLength: "3 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "leadership-communication",
        title: "Effective Leadership Communication",
        description: "Learn to communicate as a leader. Presentation skills, difficult conversations, and building influence.",
        type: "video",
        difficulty: "beginner",
        estimatedTime: 90,
        academy: "Leadership Institute",
        author: "Toastmasters International",
        category: "Leadership",
        tags: ["communication", "leadership", "public-speaking"],
        rating: 4.7,
        ratingCount: 3456,
        views: 34567,
        downloads: 7890,
        shares: 3456,
        videoLength: "1.5 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "sqlalchemy-orm",
        title: "SQLAlchemy ORM Tutorial",
        description: "Database ORM with Python. Map Python classes to database tables with SQLAlchemy.",
        type: "video",
        difficulty: "intermediate",
        estimatedTime: 180,
        academy: "Data Science Hub",
        author: "Tech with Tim",
        category: "Databases",
        tags: ["sqlalchemy", "databases", "python"],
        rating: 4.4,
        ratingCount: 876,
        views: 8765,
        downloads: 1876,
        shares: 456,
        videoLength: "3 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "docker-containerization",
        title: "Docker and Containerization",
        description: "Master Docker for building and deploying applications. Containers, images, and orchestration.",
        type: "video",
        difficulty: "intermediate",
        estimatedTime: 240,
        academy: "AI Masters",
        author: "Bret Fisher",
        category: "DevOps",
        tags: ["docker", "containerization", "devops"],
        rating: 4.6,
        ratingCount: 2345,
        views: 23456,
        downloads: 5432,
        shares: 2123,
        videoLength: "4 hours",
        language: "en",
        isPublished: true,
    },
    
    // ============ RESEARCH PAPERS (8) ============
    {
        slug: "attention-is-all-you-need",
        title: "Attention Is All You Need",
        description: "Landmark paper introducing the Transformer architecture. Foundation for modern NLP models like BERT and GPT.",
        type: "paper",
        difficulty: "advanced",
        estimatedTime: 120,
        academy: "AI Masters",
        author: "Vaswani et al.",
        category: "NLP",
        tags: ["transformers", "nlp", "attention"],
        rating: 4.8,
        ratingCount: 5234,
        views: 45321,
        downloads: 9876,
        shares: 4321,
        pageCount: 15,
        language: "en",
        isPublished: true,
    },
    {
        slug: "bert-pre-training",
        title: "BERT: Pre-training of Deep Bidirectional Transformers",
        description: "BERT pre-training methodology for bidirectional representations. Key paper in transfer learning for NLP.",
        type: "paper",
        difficulty: "advanced",
        estimatedTime: 90,
        academy: "AI Masters",
        author: "Devlin et al.",
        category: "NLP",
        tags: ["bert", "nlp", "pre-training"],
        rating: 4.7,
        ratingCount: 3456,
        views: 34567,
        downloads: 6789,
        shares: 2345,
        pageCount: 13,
        language: "en",
        isPublished: true,
    },
    {
        slug: "resnet-deep-residual",
        title: "Deep Residual Learning for Image Recognition",
        description: "Introduction of ResNet architecture with skip connections. Breakthrough in training very deep neural networks.",
        type: "paper",
        difficulty: "advanced",
        estimatedTime: 75,
        academy: "AI Masters",
        author: "He et al.",
        category: "Computer Vision",
        tags: ["cnn", "residual-networks", "computer-vision"],
        rating: 4.8,
        ratingCount: 4321,
        views: 56789,
        downloads: 12345,
        shares: 5678,
        pageCount: 12,
        language: "en",
        isPublished: true,
    },
    {
        slug: "yolo-real-time-detection",
        title: "You Only Look Once: Unified Real-Time Object Detection",
        description: "YOLO object detection system for real-time detection. Treats detection as regression problem.",
        type: "paper",
        difficulty: "advanced",
        estimatedTime: 90,
        academy: "AI Masters",
        author: "Redmon et al.",
        category: "Computer Vision",
        tags: ["object-detection", "yolo", "real-time"],
        rating: 4.7,
        ratingCount: 2345,
        views: 23456,
        downloads: 5432,
        shares: 1876,
        pageCount: 10,
        language: "en",
        isPublished: true,
    },
    {
        slug: "gpt-language-models",
        title: "Language Models are Unsupervised Multitask Learners",
        description: "GPT-2 paper showing unsupervised pre-training for multiple tasks. Foundation for modern large language models.",
        type: "paper",
        difficulty: "advanced",
        estimatedTime: 100,
        academy: "AI Masters",
        author: "Radford et al.",
        category: "NLP",
        tags: ["gpt", "language-models", "nlp"],
        rating: 4.8,
        ratingCount: 5678,
        views: 67890,
        downloads: 14567,
        shares: 6789,
        pageCount: 9,
        language: "en",
        isPublished: true,
    },
    {
        slug: "xgboost-gradient-boosting",
        title: "XGBoost: A Scalable Tree Boosting System",
        description: "XGBoost algorithm for extreme gradient boosting. One of the most popular machine learning algorithms.",
        type: "paper",
        difficulty: "intermediate",
        estimatedTime: 60,
        academy: "Data Science Hub",
        author: "Chen & Guestrin",
        category: "Machine Learning",
        tags: ["xgboost", "boosting", "machine-learning"],
        rating: 4.6,
        ratingCount: 1234,
        views: 12345,
        downloads: 2987,
        shares: 876,
        pageCount: 7,
        language: "en",
        isPublished: true,
    },
    {
        slug: "gan-generative-models",
        title: "Generative Adversarial Networks",
        description: "GANs framework for training generative models. Introduction to adversarial training.",
        type: "paper",
        difficulty: "advanced",
        estimatedTime: 100,
        academy: "AI Masters",
        author: "Goodfellow et al.",
        category: "Deep Learning",
        tags: ["gan", "generative-models", "deep-learning"],
        rating: 4.7,
        ratingCount: 4567,
        views: 45678,
        downloads: 9123,
        shares: 3456,
        pageCount: 9,
        language: "en",
        isPublished: true,
    },
    {
        slug: "dropout-regularization",
        title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
        description: "Dropout regularization technique. Simple and effective method to improve neural network generalization.",
        type: "paper",
        difficulty: "intermediate",
        estimatedTime: 50,
        academy: "AI Masters",
        author: "Hinton et al.",
        category: "Deep Learning",
        tags: ["dropout", "regularization", "neural-networks"],
        rating: 4.6,
        ratingCount: 2345,
        views: 23456,
        downloads: 5234,
        shares: 1234,
        pageCount: 8,
        language: "en",
        isPublished: true,
    },
    
    // ============ PODCASTS (8) ============
    {
        slug: "lex-fridman-ai-podcast",
        title: "Lex Fridman AI Podcast",
        description: "Long-form conversations about AI, consciousness, and the future. Interviews with leading researchers and thinkers.",
        type: "podcast",
        difficulty: "beginner",
        estimatedTime: 180,
        academy: "AI Masters",
        author: "Lex Fridman",
        category: "AI",
        tags: ["ai", "podcast", "interviews"],
        rating: 4.8,
        ratingCount: 8234,
        views: 89234,
        downloads: 23456,
        shares: 12345,
        duration: "3 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "data-stories-podcast",
        title: "Data Stories",
        description: "Podcast about data visualization and storytelling. Episodes on visual analytics and design.",
        type: "podcast",
        difficulty: "beginner",
        estimatedTime: 60,
        academy: "Data Science Hub",
        author: "Enrico Bertini & Moritz Stefaner",
        category: "Data Science",
        tags: ["visualization", "data", "podcast"],
        rating: 4.5,
        ratingCount: 1234,
        views: 12345,
        downloads: 3456,
        shares: 876,
        duration: "1 hour",
        language: "en",
        isPublished: true,
    },
    {
        slug: "linear-digressions",
        title: "Linear Digressions",
        description: "Podcast about machine learning and AI. Episodes on algorithms, applications, and industry trends.",
        type: "podcast",
        difficulty: "intermediate",
        estimatedTime: 90,
        academy: "AI Masters",
        author: "Katie Malone & Ben Jaffe",
        category: "Machine Learning",
        tags: ["machine-learning", "podcast", "ai"],
        rating: 4.6,
        ratingCount: 2345,
        views: 23456,
        downloads: 5678,
        shares: 1876,
        duration: "1.5 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "how-to-fail-podcast",
        title: "How to Fail",
        description: "Stories of failure and learning from entrepreneurs and business leaders. Practical wisdom from experience.",
        type: "podcast",
        difficulty: "beginner",
        estimatedTime: 75,
        academy: "Business Academy",
        author: "Elizabeth Day",
        category: "Business",
        tags: ["entrepreneurship", "business", "podcast"],
        rating: 4.7,
        ratingCount: 3456,
        views: 34567,
        downloads: 7890,
        shares: 2345,
        duration: "1.25 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "the-tim-ferriss-show",
        title: "The Tim Ferriss Show",
        description: "Long-form conversations with top performers across business, technology, and personal development.",
        type: "podcast",
        difficulty: "beginner",
        estimatedTime: 180,
        academy: "Leadership Institute",
        author: "Tim Ferriss",
        category: "Personal Development",
        tags: ["podcast", "interviews", "leadership"],
        rating: 4.7,
        ratingCount: 12345,
        views: 234567,
        downloads: 45678,
        shares: 23456,
        duration: "3 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "nlp-highlights",
        title: "NLP Highlights",
        description: "Podcast discussing latest NLP research papers. Host interviews researchers about their work.",
        type: "podcast",
        difficulty: "intermediate",
        estimatedTime: 120,
        academy: "AI Masters",
        author: "Allen Institute for AI",
        category: "NLP",
        tags: ["nlp", "research", "podcast"],
        rating: 4.6,
        ratingCount: 876,
        views: 8765,
        downloads: 1987,
        shares: 543,
        duration: "2 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "the-future-of-ai",
        title: "The Future of AI Podcast",
        description: "Discussions on AI capabilities, limitations, and impact on society. Expert opinions on AI safety and ethics.",
        type: "podcast",
        difficulty: "beginner",
        estimatedTime: 90,
        academy: "AI Masters",
        author: "AI Leaders",
        category: "AI Ethics",
        tags: ["ai", "ethics", "podcast"],
        rating: 4.5,
        ratingCount: 1876,
        views: 18765,
        downloads: 3456,
        shares: 876,
        duration: "1.5 hours",
        language: "en",
        isPublished: true,
    },
    {
        slug: "product-hunt-makers",
        title: "Product Hunt Makers",
        description: "Interviews with makers and entrepreneurs. Lessons from building products and growing companies.",
        type: "podcast",
        difficulty: "beginner",
        estimatedTime: 60,
        academy: "Business Academy",
        author: "Product Hunt",
        category: "Entrepreneurship",
        tags: ["startup", "entrepreneurship", "podcast"],
        rating: 4.4,
        ratingCount: 1234,
        views: 12345,
        downloads: 2345,
        shares: 654,
        duration: "1 hour",
        language: "en",
        isPublished: true,
    },
    
    // ============ ARTICLES (7) ============
    {
        slug: "understanding-transformers",
        title: "Understanding Transformers: Illustrated Guide",
        description: "Visual guide to understanding how transformers work. Breaks down attention mechanism and multi-head attention.",
        type: "article",
        difficulty: "intermediate",
        estimatedTime: 45,
        academy: "AI Masters",
        author: "Jay Alammar",
        category: "NLP",
        tags: ["transformers", "attention", "nlp"],
        rating: 4.9,
        ratingCount: 9876,
        views: 123456,
        downloads: 23456,
        shares: 12345,
        language: "en",
        isPublished: true,
    },
    {
        slug: "pandas-data-manipulation",
        title: "Pandas for Data Manipulation",
        description: "Complete guide to pandas library. DataFrames, Series, groupby, merge, and time series operations.",
        type: "article",
        difficulty: "beginner",
        estimatedTime: 60,
        academy: "Data Science Hub",
        author: "DataCamp",
        category: "Data Science",
        tags: ["pandas", "python", "data-manipulation"],
        rating: 4.7,
        ratingCount: 3456,
        views: 34567,
        downloads: 7890,
        shares: 3456,
        language: "en",
        isPublished: true,
    },
    {
        slug: "a-guide-to-sql-joins",
        title: "A Visual Guide to SQL Joins",
        description: "Visual explanation of different SQL join types. Inner, left, right, full, and cross joins with examples.",
        type: "article",
        difficulty: "beginner",
        estimatedTime: 30,
        academy: "Data Science Hub",
        author: "Jeff Atwood",
        category: "Databases",
        tags: ["sql", "databases", "joins"],
        rating: 4.8,
        ratingCount: 5432,
        views: 67890,
        downloads: 12345,
        shares: 5678,
        language: "en",
        isPublished: true,
    },
    {
        slug: "git-branching-strategies",
        title: "Git Branching Strategies",
        description: "Guide to effective git workflows. Feature branches, hotfixes, and release branches.",
        type: "article",
        difficulty: "intermediate",
        estimatedTime: 45,
        academy: "AI Masters",
        author: "Vincent Driessen",
        category: "DevOps",
        tags: ["git", "version-control", "workflow"],
        rating: 4.6,
        ratingCount: 2345,
        views: 23456,
        downloads: 4567,
        shares: 1234,
        language: "en",
        isPublished: true,
    },
    {
        slug: "pyramid-principle",
        title: "The Pyramid Principle: Clear Communication",
        description: "Framework for clear and logical communication. Organize ideas hierarchically for maximum impact.",
        type: "article",
        difficulty: "beginner",
        estimatedTime: 40,
        academy: "Leadership Institute",
        author: "Barbara Minto",
        category: "Communication",
        tags: ["communication", "writing", "presentation"],
        rating: 4.7,
        ratingCount: 4567,
        views: 45678,
        downloads: 8934,
        shares: 3456,
        language: "en",
        isPublished: true,
    },
    {
        sql_slug: "oop-design-patterns",
        title: "Object-Oriented Design Patterns",
        description: "Essential design patterns for OOP. Singleton, Factory, Observer, Strategy patterns and more.",
        type: "article",
        difficulty: "intermediate",
        estimatedTime: 90,
        academy: "AI Masters",
        author: "GoF Design Patterns",
        category: "Software Design",
        tags: ["design-patterns", "oop", "software-design"],
        rating: 4.5,
        ratingCount: 1876,
        views: 18765,
        downloads: 3456,
        shares: 876,
        language: "en",
        isPublished: true,
    },
    {
        slug: "writing-effective-api",
        title: "Writing Effective API Documentation",
        description: "Best practices for API documentation. Examples, error codes, SDKs, and developer experience.",
        type: "article",
        difficulty: "intermediate",
        estimatedTime: 35,
        academy: "Business Academy",
        author: "Stripe Engineering",
        category: "Technical Writing",
        tags: ["api", "documentation", "developer-experience"],
        rating: 4.6,
        ratingCount: 2345,
        views: 23456,
        downloads: 4567,
        shares: 1234,
        language: "en",
        isPublished: true,
    },
];

/* ============================================================
   BATCH UPLOAD FUNCTION
============================================================ */

/**
 * Upload resources to Firestore in batches
 * @returns {Promise<number>} Number of resources uploaded
 */
async function seedResources() {
    try {
        console.log("🌱 Starting resource seeding...");
        console.log(`📊 Total resources to upload: ${SAMPLE_RESOURCES.length}`);

        let uploadedCount = 0;
        const batches = Math.ceil(SAMPLE_RESOURCES.length / BATCH_SIZE);

        for (let i = 0; i < batches; i++) {
            const batch = writeBatch(db);
            const start = i * BATCH_SIZE;
            const end = Math.min(start + BATCH_SIZE, SAMPLE_RESOURCES.length);
            const batchResources = SAMPLE_RESOURCES.slice(start, end);

            batchResources.forEach(resource => {
                // Generate a document ID
                const docRef = doc(
                    collection(db, RESOURCES_COLLECTION)
                );

                // Add timestamps
                const dataToSave = {
                    ...resource,
                    resourceId: docRef.id,
                    createdAt: Timestamp.now(),
                    updatedAt: Timestamp.now(),
                    createdBy: "system_seeder",
                };

                batch.set(docRef, dataToSave);
            });

            // Commit batch
            await batch.commit();
            uploadedCount += batchResources.length;

            console.log(
                `✅ Batch ${i + 1}/${batches} uploaded (${uploadedCount}/${SAMPLE_RESOURCES.length})`
            );
        }

        console.log(
            `\n🎉 Successfully uploaded ${uploadedCount} resources to Firestore!`
        );
        return uploadedCount;
    } catch (error) {
        console.error("❌ Error seeding resources:", error);
        throw error;
    }
}

/* ============================================================
   EXPORTS
============================================================ */

export { seedResources, SAMPLE_RESOURCES };

export default {
    seedResources,
    SAMPLE_RESOURCES,
};
